//
// Created by 40906 on 2021/9/18.
//

#ifndef HELLOWORLD_BLOCKCHAIN_CPP_BLOCKTOOL_H
#define HELLOWORLD_BLOCKCHAIN_CPP_BLOCKTOOL_H


namespace BlockTool {

};


#endif //HELLOWORLD_BLOCKCHAIN_CPP_BLOCKTOOL_H
